### ISSUE TITLE
Programmatically list the pages to render

### ISSUE THREAD

**Issue by karellm** [SolarLiner/vue-cli-plugin-prerender-spa#3]
**Is your feature request related to a problem? Please describe.**
I'm trying to see if Vue is a good tool to generate static websites. I tried Nuxt but the i18n implementation with `nuxt-i18n` is broken so I dropped it. And the CLI 3 gives me the feeling Nuxt isn't needed as much anymore. That said, one thing I liked was their generate config:

```js
{
generate: {
    routes: function () {
      return axios.get('https://jsonplaceholder.typicode.com/users')
      .then((res) => {
        return res.data.map((user) => {
            return {
              route: '/projects/' + user.id,
              payload: user
            }
        })
      })
    }
  }
}
```

**Describe the solution you'd like**
A function hook to configure the routes to prerender.

**Describe alternatives you've considered**
I would write a script that parses my folder or `router.js` and update the `.prerender-spa.json` automatically.

**Comment by SolarLiner** [comment]
I'm sorry but this is out of the scope of this plugin, and of pre-rendering in general. The goal of pre-rendering is to have a subset of pages that load fast, and not pre-render the whole app from their different routes. Furthermore, lots of features that Nuxt.js provides would be missing, from server-side data fetch, to parametric routes, etc. Generating a whole static website by loading instances of Chrome is inefficient and will *not* produce satisfactory results.

There are other ways of generating static websites with Vue, from the Vue SSR template to VuePress. And those are not usable, then you have a great idea of a Vue CLI plugin to write, that integrates `vue-server-renderer` in order to generate a static website. But ultimately, this is out of the scope of this plugin.

If you decide to try and make it I'll try and come work on it when I can. Otherwise I can put it in my TODO list, but with a low priority. Sorry :/

**Comment by karellm** [comment]
I understand, thanks for the detailed answer. I will consider a Vue CLI plugin and let you know if I go down that route. I would greatly appreciate some help!

**Comment by SolarLiner** [comment]
Just a heads up @karellm during some quick research I found https://github.com/egoist/saber.js/ which may or may not be what you want for your project.

**Comment by karellm** [comment]
Thanks I'll check it out!
