### ISSUE TITLE
Getting ERROR  TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string

### ISSUE THREAD

**Issue by erajasekar** [SolarLiner/vue-cli-plugin-prerender-spa#8]
**Describe the bug**
Getting ERROR  TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string

**To Reproduce**
1. Followed installation instructions.
2. Ran command `npm run build`.

**Expected behavior**
Successful build.

**Output**
But getting error..

npm run build
```
> vue-cli-service build

⠋  Building for production... ERROR  TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string
    at assertPath (path.js:28:11)
    at Object.join (path.js:1244:7)
    at api.chainWebpack.config (~/node_modules/vue-cli-plugin-prerender-spa/index.js:34:16)
```

Contents of my .prerender-spa.json

```json
{
"renderRoutes":["/","/about"],
"useRenderEvent":true,
"headless":true,
"onlyProduction":true
}
```

**Additional context**
Vue version: 2.5.16
Vue CLI version: 3.0.0-beta.15

**Comment by erajasekar** [comment]
I am missing anything. Can you help resolve this issue?

**Comment by SolarLiner** [comment]
The configuration file looks to be default. I can't reproduce the bug with a test project though.

It seems like the line that fails is an attempt to resolve the path to the generated index file - and it only uses Vue configuration options, mainly the output directory and index path. Did you change those values and can you show them to me?

**Comment by erajasekar** [comment]
Thanks for checking,

I did not change any of those values. I tried it on a new vanilla project and still hit the same error:

Here is the code on the GitHub if you want to check https://github.com/erajasekar/doculet4/tree/pre-render

I suspect either it could be a version difference or environment settings on my machine. What version of vue and vue-cli do you have for your test project?

**Comment by SolarLiner** [comment]
I can reproduce the bug with your codebase, so that's progress...

**Comment by SolarLiner** [comment]
So by default, the Vue CLI passes the "index path" option to the plugin, which is then used to tell the prerendering plugin where to write the generated markup. It appears by default, since creating a new project just works - but in your case, it doesn't pass that variable to the plugin.

The culprit is the version of the CLI service you used - you're stuck under **3.0.0-beta.15** instead of the latest version (which I am in, 3.0.4). Why I didn't check that first, is unknown to me :laughing: 

Update your CLI dependencies to 3.0.4 and it should work like a charm!

**Comment by erajasekar** [comment]
Yep worked great with the latest version. Thanks a lot looking into and also for the very useful plugin.
